"""initial

Revision ID: 22ddf89ce690
Revises: 
Create Date: 2026-05-25 15:30:04.575722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22ddf89ce690'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing = inspector.get_table_names()

    if 'jobs' not in existing:
        op.create_table('jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('topic', sa.Text(), nullable=False),
        sa.Column('tone', sa.Text(), nullable=False),
        sa.Column('word_count', sa.Integer(), nullable=False),
        sa.Column('instructions', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('current_node', sa.Text(), nullable=True),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    else:
        existing_indexes = [i['name'] for i in inspector.get_indexes('jobs')]
        if 'ix_jobs_status' not in existing_indexes:
            op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)

    if 'settings' not in existing:
        op.create_table('settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('default_tone', sa.Text(), nullable=False),
        sa.Column('default_word_count', sa.Integer(), nullable=False),
        sa.Column('password_hash', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
