"""add_logs_to_jobs

Revision ID: 899b0edc74e4
Revises: b9e70425e616
Create Date: 2026-06-03 10:22:58.551211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899b0edc74e4'
down_revision: Union[str, Sequence[str], None] = 'b9e70425e616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'logs')
    # ### end Alembic commands ###
